### ISSUE TITLE
Enhancement: Optional unwrapping

### ISSUE THREAD

**Issue by DanCardin** [litestar-org/type-lens#8]
### Summary

Given some `TypeView(Optional[str])` or `TypeView(Union[str, int, None])`, it would be convenient to be able to produce another `TypeView` without the optionality.

### Basic Example

```python
view = TypeView(Optional[str])
result = opt_str.unwrap_optional()
assert TypeView(str) == result

view = TypeView(Union[str, int, None])
stuff = view.unwrap_optional()
assert TypeView(Union[str, int]) == result

# and then probably
view = TypeView(int)
stuff = view.unwrap_optional()
assert TypeView(int) == result
```

### Drawbacks and Impact

Perhaps the name could or could not imply that it was simply getting rid of the optional without re-wrapping a `TypeView`. I'm not at all married to my suggested name.

I'd personally only be using it incontexts where normalizing away the optional is the an inconvenient step in further introspection of the inner types.

---

Happy to supply a candidate impl, if you're into the suggestion.

**Comment by peterschutt** [comment]
Without it being specific to optional, you can get this with:

```py
view = TypeView(Optional[str])
assert TypeView(str) == view.inner_types[0]
```

What do you think `unwrap_optional()` should do if the TypeView doesn't represent an optional type? Error, or return self?

**Comment by DanCardin** [comment]
My third example is that case.

Either you'd be forced to check `if view.is_optional` as a guard in order to use the method in the first place, whether it errors or returned `None`. Thus I think it'd probably be most useful to return self. But with that said, I wouldn't be mad at any of the above.

And yea
